In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
rawdata = files.upload()

Saving Fish poc3 dataset.csv to Fish poc3 dataset.csv


In [ ]:
df=pd.read_csv('Fish poc3 dataset.csv')
df

Species  Weight  Length1  Length2  Length3   Height   Width
0     Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1     Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2     Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3     Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4     Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...     ...      ...      ...      ...      ...     ...
154   Smelt    12.2     11.5     12.2     13.4   2.0904  1.3936
155   Smelt    13.4     11.7     12.4     13.5   2.4300  1.2690
156   Smelt    12.2     12.1     13.0     13.8   2.2770  1.2558
157   Smelt    19.7     13.2     14.3     15.2   2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 7 columns]

In [ ]:
df.shape

(159, 7)

In [ ]:
df.head(2)

Species  Weight  Length1  Length2  Length3  Height   Width
0   Bream   242.0     23.2     25.4     30.0   11.52  4.0200
1   Bream   290.0     24.0     26.3     31.2   12.48  4.3056

In [ ]:
df.tail(2)

Species  Weight  Length1  Length2  Length3  Height   Width
157   Smelt    19.7     13.2     14.3     15.2  2.8728  2.0672
158   Smelt    19.9     13.8     15.0     16.2  2.9322  1.8792

In [ ]:
df.isnull().sum()

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [ ]:
df.columns

Index(['Species', 'Weight', 'Length1', 'Length2', 'Length3', 'Height',
       'Width'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Species  159 non-null    object 
 1   Weight   159 non-null    float64
 2   Length1  159 non-null    float64
 3   Length2  159 non-null    float64
 4   Length3  159 non-null    float64
 5   Height   159 non-null    float64
 6   Width    159 non-null    float64
dtypes: float64(6), object(1)
memory usage: 8.8+ KB


In [ ]:
df.describe()

Weight     Length1     Length2     Length3      Height       Width
count   159.000000  159.000000  159.000000  159.000000  159.000000  159.000000
mean    398.326415   26.247170   28.415723   31.227044    8.970994    4.417486
std     357.978317    9.996441   10.716328   11.610246    4.286208    1.685804
min       0.000000    7.500000    8.400000    8.800000    1.728400    1.047600
25%     120.000000   19.050000   21.000000   23.150000    5.944800    3.385650
50%     273.000000   25.200000   27.300000   29.400000    7.786000    4.248500
75%     650.000000   32.700000   35.500000   39.650000   12.365900    5.584500
max    1650.000000   59.000000   63.400000   68.000000   18.957000    8.142000

In [ ]:
df.head()

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340

In [ ]:
X=df.iloc[:,[1,2,3,4,5,6]]
X

Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [ ]:
x=df[['Weight','Length1','Length2','Length3','Height','Width']]
x

Weight  Length1  Length2  Length3   Height   Width
0     242.0     23.2     25.4     30.0  11.5200  4.0200
1     290.0     24.0     26.3     31.2  12.4800  4.3056
2     340.0     23.9     26.5     31.1  12.3778  4.6961
3     363.0     26.3     29.0     33.5  12.7300  4.4555
4     430.0     26.5     29.0     34.0  12.4440  5.1340
..      ...      ...      ...      ...      ...     ...
154    12.2     11.5     12.2     13.4   2.0904  1.3936
155    13.4     11.7     12.4     13.5   2.4300  1.2690
156    12.2     12.1     13.0     13.8   2.2770  1.2558
157    19.7     13.2     14.3     15.2   2.8728  2.0672
158    19.9     13.8     15.0     16.2   2.9322  1.8792

[159 rows x 6 columns]

In [ ]:
Y=df.iloc[:,[0]]
Y

Species
0     Bream
1     Bream
2     Bream
3     Bream
4     Bream
..      ...
154   Smelt
155   Smelt
156   Smelt
157   Smelt
158   Smelt

[159 rows x 1 columns]

In [ ]:
df['Species'].unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [ ]:
df['Weight'].unique()

array([ 242. ,  290. ,  340. ,  363. ,  430. ,  450. ,  500. ,  390. ,
        475. ,  600. ,  700. ,  610. ,  650. ,  575. ,  685. ,  620. ,
        680. ,  725. ,  720. ,  714. ,  850. , 1000. ,  920. ,  955. ,
        925. ,  975. ,  950. ,   40. ,   69. ,   78. ,   87. ,  120. ,
          0. ,  110. ,  150. ,  145. ,  160. ,  140. ,  169. ,  161. ,
        200. ,  180. ,  272. ,  270. ,  306. ,  540. ,  800. ,   55. ,
         60. ,   90. ,  170. ,  273. ,  300. ,    5.9,   32. ,   51.5,
         70. ,  100. ,   80. ,   85. ,  115. ,  125. ,  130. ,  135. ,
        225. ,  188. ,  197. ,  218. ,  260. ,  265. ,  250. ,  320. ,
        514. ,  556. ,  840. ,  690. ,  900. ,  820. , 1015. , 1100. ,
        345. ,  456. ,  510. ,  567. ,  770. , 1250. , 1600. , 1550. ,
       1650. ,    6.7,    7.5,    7. ,    9.7,    9.8,    8.7,   10. ,
          9.9,   12.2,   13.4,   19.7,   19.9])

In [ ]:
from sklearn.preprocessing import Normalizer
X2_L1=Normalizer(norm='l1').fit_transform(X)
X2_L1

array([[0.71993812, 0.06901886, 0.07556375, 0.08924853, 0.03427143,
        0.0119593 ],
       [0.74687292, 0.06181017, 0.06773365, 0.08035322, 0.03214129,
        0.01108874],
       [0.77523993, 0.05449481, 0.06042311, 0.07091165, 0.02822284,
        0.01070766],
       [0.77401114, 0.05607849, 0.0618356 , 0.07143078, 0.0271437 ,
        0.00950029],
       [0.80062859, 0.04934106, 0.05399588, 0.06330552, 0.02316982,
        0.00955913],
       [0.80395934, 0.04788025, 0.05306132, 0.0619942 , 0.02430173,
        0.00880318],
       [0.81905717, 0.04390146, 0.048652  , 0.05651494, 0.02322764,
        0.00864679],
       [0.7800624 , 0.05520442, 0.0600048 , 0.0700056 , 0.02534203,
        0.00938075],
       [0.80135525, 0.04914979, 0.05342368, 0.06250571, 0.02493978,
        0.00862579],
       [0.81355579, 0.04637268, 0.04995233, 0.05890144, 0.02314827,
        0.0080695 ],
       [0.80512978, 0.04813829, 0.05254531, 0.06135936, 0.02417559,
        0.00865167],
       [0.81289446, 0

In [ ]:
from sklearn import preprocessing
X_normal_normalize=preprocessing.normalize(X)
X_normal_normalize

array([[0.9814697 , 0.09409131, 0.10301376, 0.1216698 , 0.0467212 ,
        0.01630375],
       [0.98594171, 0.08159518, 0.08941471, 0.10607373, 0.04242949,
        0.01463817],
       [0.98971145, 0.06957089, 0.07713927, 0.09052949, 0.03603074,
        0.01366995],
       [0.98940629, 0.07168426, 0.07904348, 0.09130884, 0.03469736,
        0.01214408],
       [0.9923006 , 0.06115341, 0.0669226 , 0.07846098, 0.02871672,
        0.01184761],
       [0.99264075, 0.05911727, 0.06551429, 0.07654363, 0.0300051 ,
        0.0108692 ],
       [0.99401516, 0.05327921, 0.0590445 , 0.06858705, 0.02818928,
        0.01049382],
       [0.99006049, 0.07006582, 0.0761585 , 0.08885158, 0.03216427,
        0.01190611],
       [0.99240019, 0.06086721, 0.06616001, 0.07740721, 0.03088548,
        0.0106822 ],
       [0.99347998, 0.05662836, 0.06099967, 0.07192795, 0.02826768,
        0.00985413],
       [0.99275002, 0.059356  , 0.06479   , 0.075658  , 0.02980925,
        0.01066778],
       [0.99341591, 0

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (X2_L1, Y, test_size = 0.2, random_state = 1234)  # 80:20 , 70:30, # parado principle
x_train, x_test, y_train, y_test

(array([[0.67268918, 0.08251654, 0.08969189, 0.10045492, 0.0398806 ,
         0.01476687],
        [0.68021298, 0.0869161 , 0.09447403, 0.10014247, 0.02433462,
         0.0139198 ],
        [0.20781558, 0.22281258, 0.23566715, 0.25709144, 0.04704773,
         0.02956552],
        [0.8810368 , 0.0321178 , 0.03444053, 0.03644289, 0.01002179,
         0.00594019],
        [0.22330907, 0.22147867, 0.23795229, 0.25259551, 0.04167826,
         0.02298619],
        [0.87085487, 0.03622756, 0.0390143 , 0.04159203, 0.00744497,
         0.00486627],
        [0.67241306, 0.08816082, 0.09413783, 0.10422402, 0.0264729 ,
         0.01459136],
        [0.72574945, 0.07668752, 0.0822516 , 0.09144443, 0.01380811,
         0.01005889],
        [0.63372901, 0.09749677, 0.10724645, 0.11455871, 0.02978526,
         0.01718381],
        [0.6526146 , 0.09316636, 0.10216794, 0.10891913, 0.02679411,
         0.01633787],
        [0.66648368, 0.08676119, 0.09464857, 0.10726838, 0.02971334,
         0.01512484],

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier= KNeighborsClassifier(n_neighbors=5,p=2 )
classifier.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [ ]:
y_pred= classifier.predict(x_test)
y_pred

array(['Roach', 'Bream', 'Perch', 'Perch', 'Smelt', 'Perch', 'Perch',
       'Smelt', 'Perch', 'Bream', 'Bream', 'Perch', 'Perch', 'Perch',
       'Bream', 'Perch', 'Bream', 'Bream', 'Perch', 'Bream', 'Perch',
       'Bream', 'Perch', 'Smelt', 'Perch', 'Bream', 'Pike', 'Perch',
       'Smelt', 'Bream', 'Perch', 'Roach'], dtype=object)

In [ ]:
from sklearn.svm import SVC
classifier2 = SVC(kernel = 'linear', random_state = 0)
classifier2.fit(x_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear', random_state=0)

In [ ]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
cm

array([[6, 0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [2, 0, 6, 1, 2, 1, 0],
       [1, 0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [1, 0, 1, 0, 0, 0, 0]])